# Configuration options can be accessed as
#   APP_CONFIG.site_name

development: &local
    site_name: BaseApp
    site_url: "localhost:3000"

    company_name: BaseApp Inc.
    admin_email: admin@example.com

    support_name: Support
    support_email: support@example.com

    ticket_email: issues@example.com

    session_time_out: 30

production:
  <<: *local
  session_time_out: 50

staging:
  <<: *local

test:
  <<: *local

