# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: rTrac
    site_url: "rtrac.local"

    company_name: Siverti Inc.
    admin_email: admin@rtrac.com.com

    support_name: Suporte
    support_email: suporte@rtrac.com

    ticket_email: tickets@rtrac.com

    session_time_out: 30

production:
  <<: *local
  session_time_out: 50

staging:
  <<: *local

test:
  <<: *local

